"""Chrome browser tool — run Chrome in Docker with Xvfb for undetectable browsing.

Usage:
    codefreedom tools chrome init    Initialize tool profile (requires acceptance)
    codefreedom tools chrome start   Start Chrome container (Xvfb + Chromium)
    codefreedom tools chrome stop    Stop and remove Chrome container
    codefreedom tools chrome status  Show Chrome container status
    codefreedom tools chrome url     Show CDP debug URL

Settings are loaded from ~/.codefreedom/profiles/chrome.json (generated by
'codefreedom tools chrome init').  See src/codefreedom/examples/tools/chrome/
for the template with all available options.
"""

from __future__ import annotations

import argparse
import json
import subprocess

from codefreedom.config import get_codefreedom_dir
from codefreedom.env_loader import eprint
from codefreedom.cli.docker_utils import (
    check_docker_available,
    container_exists,
    container_is_running,
    ensure_image,
    resolve_data_dir,
)
from codefreedom.cli.init_utils import copy_bundled_files, find_bundled_examples
from codefreedom.cli.tool_init_utils import (
    _print_non_disclaimer,
    _print_tool_notice,
    prompt_acceptance,
)

# ── Defaults ──────────────────────────────────────────────────────────────────

_DEFAULT_IMAGE = "codefreedom:chrome"
_DEFAULT_CONTAINER_NAME = "codefreedom-tools-chrome"
_DEFAULT_PORT = 9222
_DEFAULT_DATA_DIR = "~/.codefreedom/sandbox/tools/chrome"

_CODEFREEDOM_DIR = get_codefreedom_dir()
_PROFILE_PATH = _CODEFREEDOM_DIR / "profiles" / "chrome.json"


# ── Profile loader ────────────────────────────────────────────────────────────


def _load_profile() -> dict:
    """Load chrome tool profile from ~/.codefreedom/profiles/chrome.json.

    Returns a flat dict with keys: image, container_name, port, data_dir, env.
    Any missing key falls back to the hardcoded default above.
    """
    settings: dict = {
        "image": _DEFAULT_IMAGE,
        "container_name": _DEFAULT_CONTAINER_NAME,
        "port": _DEFAULT_PORT,
        "data_dir": _DEFAULT_DATA_DIR,
        "env": {},
    }

    if not _PROFILE_PATH.exists():
        return settings

    try:
        with open(_PROFILE_PATH, encoding="utf-8") as f:
            raw = json.load(f)
    except (json.JSONDecodeError, OSError) as exc:
        eprint(f"[CHROME] Warning: failed to read {_PROFILE_PATH}: {exc}")
        return settings

    chrome_cfg = raw.get("chrome", {})
    if not isinstance(chrome_cfg, dict):
        return settings

    # Merge — profile values override defaults
    if isinstance(chrome_cfg.get("image"), str) and chrome_cfg["image"]:
        settings["image"] = chrome_cfg["image"]
    if (
        isinstance(chrome_cfg.get("container_name"), str)
        and chrome_cfg["container_name"]
    ):
        settings["container_name"] = chrome_cfg["container_name"]
    if isinstance(chrome_cfg.get("port"), int) and chrome_cfg["port"] > 0:
        settings["port"] = chrome_cfg["port"]
    if isinstance(chrome_cfg.get("data_dir"), str) and chrome_cfg["data_dir"]:
        settings["data_dir"] = chrome_cfg["data_dir"]
    if isinstance(chrome_cfg.get("env"), dict):
        settings["env"] = chrome_cfg["env"]

    return settings


# ── Init ────────────────────────────────────────────────────────────────────


def init_tool() -> int:
    """Initialize the chrome tool profile from bundled examples.

    Only copies files into an empty target — if profile already exists,
    directs user to docs and example configs for manual merging.

    Requires user acceptance of third-party components.
    """
    if not prompt_acceptance("chrome"):
        return 1

    bundled = find_bundled_examples(__file__)
    tools_src = bundled / "tools" / "chrome"
    profiles_dst_dir = _CODEFREEDOM_DIR / "profiles"

    created = copy_bundled_files(
        tools_src,
        profiles_dst_dir,
        label="chrome init",
        docs_url="https://nilayparikh.github.io/codefreedom/tools/chrome/",
        examples_url="https://github.com/nilayparikh/codefreedom/tree/main/src/codefreedom/examples/tools/chrome/",
    )

    print()
    if created:
        print(f"[chrome init] Done — {len(created)} created.")
    _print_non_disclaimer()
    return 0


# ── Actions ────────────────────────────────────────────────────────────────────


def start(settings: dict) -> int:
    """Start the Chrome browser container. Returns exit code."""
    # ── Init gate: refuse to start if tool not initialized ───────────────
    if not _PROFILE_PATH.exists():
        eprint("[chrome] Tool not initialized.")
        eprint("         Run:  codefreedom tools chrome init")
        eprint(
            "         Docs: https://nilayparikh.github.io/codefreedom/claude-code/tools/"
        )
        return 1

    # ── Third-party notice on every start ────────────────────────────────
    _print_tool_notice("chrome")

    image = settings["image"]
    container_name = settings["container_name"]
    port = settings["port"]
    data_dir = settings["data_dir"]
    env_vars = settings.get("env", {})

    if container_is_running(container_name):
        eprint(f"[CHROME] Container '{container_name}' is already running.")
        return 0

    # Check if Docker is available
    if not check_docker_available():
        eprint("[ERROR] Docker not found. Install Docker and try again.")
        return 1

    # Resolve & create data directory
    resolved_data = resolve_data_dir(data_dir)
    eprint(f"[CHROME] Using data dir: {resolved_data}")

    # Ensure shared tools cache directory exists (used by Chrome DevTools MCP, etc.)
    tools_cache = get_codefreedom_dir() / "sandbox" / "tools" / ".cache"
    tools_cache.mkdir(parents=True, exist_ok=True)

    # Remove existing container if stopped
    if container_exists(container_name):
        eprint(f"[CHROME] Removing existing container '{container_name}'...")
        subprocess.run(
            ["docker", "rm", "-f", container_name],
            capture_output=True,
            timeout=15,
            check=False,
        )

    # Ensure image is available
    if not ensure_image(
        image,
        label="CHROME",
        build_tip="docker build -t codefreedom:chrome -f docker/chrome/Dockerfile.Chrome docker/chrome/",
        profile_path="~/.codefreedom/profiles/chrome.json",
    ):
        return 1

    # Build environment flags
    env_flags: list[str] = []
    for key, val in env_vars.items():
        if key in env_vars:
            env_flags.extend(["-e", f"{key}={val}"])
    # Ensure DISPLAY is set
    if "DISPLAY" not in env_vars:
        env_flags.extend(["-e", "DISPLAY=:99"])

    # Start container
    eprint(f"[CHROME] Starting container '{container_name}'...")
    create = subprocess.run(
        [
            "docker",
            "run",
            "-d",
            "--name",
            container_name,
            "--network",
            "host",
            "--ipc=host",
            "--cap-add=SYS_ADMIN",
            "--init",
            "--restart",
            "unless-stopped",
            "-v",
            f"{resolved_data}:/data/chrome",
            "-v",
            f"{tools_cache}:/home/vscode/.cache",
            *env_flags,
            image,
        ],
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    if create.returncode != 0:
        eprint("[ERROR] Failed to start Chrome container.")
        if create.stderr:
            eprint(f"   {create.stderr.strip()}")
        return 1

    eprint("   [OK] Container started.")
    eprint(f"   CDP debug URL: http://127.0.0.1:{port}")
    eprint(
        f"   DevTools:      devtools://devtools/bundled/inspector.html?ws=127.0.0.1:{port}"
    )
    return 0


def stop(settings: dict) -> int:
    """Stop and remove the Chrome container. Returns exit code."""
    container_name = settings["container_name"]

    if not container_exists(container_name):
        eprint(f"[CHROME] Container '{container_name}' does not exist.")
        return 0

    eprint(f"[CHROME] Stopping container '{container_name}'...")
    subprocess.run(
        ["docker", "stop", container_name],
        capture_output=True,
        timeout=30,
        check=False,
    )
    subprocess.run(
        ["docker", "rm", container_name],
        capture_output=True,
        timeout=15,
        check=False,
    )
    eprint("   [OK] Container stopped and removed.")
    return 0


def status(settings: dict) -> int:
    """Show Chrome container status. Returns exit code."""
    container_name = settings["container_name"]
    port = settings["port"]

    if not container_exists(container_name):
        eprint("[CHROME] No Chrome container found.")
        eprint("   Start one with:  codefreedom tools chrome start")
        return 0

    try:
        result = subprocess.run(
            [
                "docker",
                "ps",
                "-a",
                "--filter",
                f"name={container_name}",
                "--format",
                "{{.Names}}\t{{.Status}}\t{{.CreatedAt}}",
            ],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
        for line in result.stdout.strip().split("\n"):
            if line:
                name, status_line, created = line.split("\t", 2)
                marker = "[RUNNING]" if "Up " in status_line else "[STOPPED]"
                eprint(f"[CHROME] {marker} {name}")
                eprint(f"         Status: {status_line}")
                eprint(f"         Created: {created}")

        if container_is_running(container_name):
            eprint(f"         CDP URL: http://127.0.0.1:{port}")
            eprint(
                f"         DevTools: devtools://devtools/bundled/inspector.html?ws=127.0.0.1:{port}"
            )
    except (subprocess.SubprocessError, FileNotFoundError) as e:
        eprint(f"[ERROR] Failed to get container status: {e}")
        return 1
    return 0


def url(settings: dict) -> int:
    """Print the CDP debug URL. Returns exit code."""
    container_name = settings["container_name"]
    port = settings["port"]

    if not container_is_running(container_name):
        eprint("[CHROME] Chrome container is not running.")
        eprint("   Start it with:  codefreedom tools chrome start")
        return 1

    print(f"http://127.0.0.1:{port}")
    return 0


def run(args: argparse.Namespace) -> int:
    """Execute the chrome tool subcommand. Returns exit code."""
    settings = _load_profile()

    # CLI --port flag overrides profile and defaults
    if hasattr(args, "port") and args.port:
        settings["port"] = args.port

    action = args.action or "status"

    if action == "start":
        return start(settings)
    elif action == "stop":
        return stop(settings)
    elif action == "status":
        return status(settings)
    elif action == "url":
        return url(settings)
    else:
        eprint(f"[ERROR] Unknown action: {action}")
        eprint("   Valid actions: start, stop, status, url")
        return 1
