"""Code agent subcommand — launch with profile-based routing and sandboxing.

Usage:
    codefreedom claude [--profile NAME] [--sandbox] [--list-profiles] [agent-args...]
    cf cc [same]

VS Code integration: see `codefreedom vscode claude config`.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from codefreedom.config import resolve_profiles_path
from codefreedom.env_loader import eprint, load_env_chain
from codefreedom.launcher import run_docker, run_local
from codefreedom.profiles import (
    ProfileError,
    get_profile_sandbox_images,
    get_profile_tools,
    list_profiles,
    load_profile_env,
    load_profiles,
)
from codefreedom.tool_registry import acquire_tools, generate_session_id, release_tools


def init_claude() -> int:
    """Initialize Claude Code configuration via recipes.

    Bundled examples have been replaced by the recipe system.
    Use ``cf init recipe`` or ``cf init recipe --plan <name>`` instead.
    """
    from codefreedom.cli.tool_init_utils import print_help_section

    print_help_section(
        "claude init",
        [
            "Use:  cf init recipe              # install _default base recipe",
            "      cf init recipe --list        # list available recipes",
            "      cf init recipe --plan <name> # preview a recipe without applying",
            "      cf init recipe <name>        # install a specific recipe",
        ],
        docs_url="https://nilayparikh.github.io/codefreedom/recipes/",
        include_disclaimer=True,
    )
    return 0


# VS Code settings generation moved to codefreedom.cli.vscode.


def cmd_config(args: argparse.Namespace) -> int:
    """Resolve profile env vars and print for standalone Claude Code use.

    Loads the full env chain (component-specific → shared → workspace →
    system), resolves the selected profile's env vars, and outputs them
    as source-able export statements (bash) or $env: assignments (PowerShell).

    Supports --out <file> for file output (recommended — values may include
    secrets), or stdout with interactive confirmation.
    """
    workspace_dir = Path.cwd()

    # ── Load env chain ─────────────────────────────────────────────────────
    eprint("[ENV] Loading configuration...")
    base_env = load_env_chain(workspace_dir, component="claude")

    # ── Load profile ───────────────────────────────────────────────────────
    profile_name = getattr(args, "profile", None) or "default"
    profiles_path = resolve_profiles_path()

    profile_env: dict[str, str] = {}
    if profiles_path.exists():
        try:
            profiles_dict = load_profiles(profiles_path)
            profile_env = load_profile_env(
                profile_name,
                profiles_path,
                base_env,
                mode="local",
                profiles=profiles_dict,
            )
        except ProfileError as exc:
            eprint(f"[ERROR] {exc}")
            return 1
    elif profile_name != "default":
        eprint(
            f"[ERROR] Profile '{profile_name}' requested but no profiles file found."
        )
        return 1
    else:
        eprint("[ERROR] No profiles file found. Run `codefreedom claude init` first.")
        return 1

    if not profile_env:
        eprint("[ERROR] Profile resolved to an empty environment.")
        return 1

    # ── Determine format ────────────────────────────────────────────────────
    is_ps = getattr(args, "powershell", False)
    out_path = getattr(args, "out", None)

    # ── Build output ────────────────────────────────────────────────────────
    lines: list[str] = []
    if is_ps:
        lines.append("<#")
        lines.append("  Claude Code environment variables -- generated by codefreedom")
        lines.append(f"  Profile: {profile_name}")
        lines.append(
            "  WARNING: This file may contain sensitive values (API keys, tokens)."
        )
        lines.append("#>")
        lines.append("")
        for key in sorted(profile_env):
            val = profile_env[key]
            escaped = val.replace('"', '`"')
            lines.append(f'$env:{key} = "{escaped}"')
    else:
        lines.append("#!/usr/bin/env bash")
        lines.append("# Claude Code environment variables -- generated by codefreedom")
        lines.append(f"# Profile: {profile_name}")
        lines.append(
            "# WARNING: This file may contain sensitive values (API keys, tokens)."
        )
        lines.append("")
        for key in sorted(profile_env):
            val = profile_env[key]
            escaped = val.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'export {key}="{escaped}"')

    output = "\n".join(lines) + "\n"

    # ── Warning about secrets ───────────────────────────────────────────────
    warning = (
        "[CONFIG] WARNING: The generated output may contain sensitive values\n"
        "[CONFIG] (API keys, tokens, secrets). Review before sharing or committing.\n"
        "[CONFIG] Use --out <file> to write to a file for better security.\n"
    )

    if out_path:
        eprint(warning)
        out_file = Path(out_path)
        out_file.parent.mkdir(parents=True, exist_ok=True)
        out_file.write_text(output, encoding="utf-8")
        out_file.chmod(0o600)
        eprint(f"[CONFIG] Written to {out_file.resolve()}")
        return 0

    # ── stdout path: warn and confirm ──────────────────────────────────────
    eprint(warning)
    eprint("[CONFIG] Outputting to stdout. Values may be captured in terminal logs.")
    try:
        response = input("[CONFIG] Proceed? [y/N] ")
        if response.lower() not in ("y", "yes"):
            eprint("[CONFIG] Aborted.")
            return 1
    except (EOFError, KeyboardInterrupt):
        eprint()
        eprint("[CONFIG] Aborted.")
        return 1

    print(output)
    return 0


def run(args: argparse.Namespace) -> int:
    """Execute the claude subcommand. Returns exit code."""

    # Fast-path flags (no env loading needed)
    if args.list_profiles:
        profiles_path = resolve_profiles_path()
        profiles = list_profiles(profiles_path)
        if not profiles:
            eprint("[PROFILES] No profiles found.")
            return 0
        eprint(f"[PROFILES] Available profiles ({profiles_path}):\n")
        for p in profiles:
            override_word = "override" if len(p["env_keys"]) == 1 else "overrides"
            inheritance = (
                "standalone"
                if p["standalone"]
                else f"inherits from 'default' — {len(p['env_keys'])} {override_word}"
            )
            eprint(f"  {p['name']}")
            eprint(f"    {p['description']}")
            eprint(f"    ({inheritance})")
            if p["env_keys"]:
                keys_summary = ", ".join(p["env_keys"][:5])
                if len(p["env_keys"]) > 5:
                    keys_summary += ", …"
                eprint(f"    sets: {keys_summary}")
            if p.get("sandbox_env_keys"):
                eprint(f"    sandbox: {', '.join(p['sandbox_env_keys'])}")
            if p.get("local_env_keys"):
                eprint(f"    local: {', '.join(p['local_env_keys'])}")
            if p.get("tools"):
                eprint(f"    tools: {', '.join(p['tools'])}")
            eprint()
        return 0

    # ── Load env chain ─────────────────────────────────────────────────────
    workspace_dir = Path.cwd()
    eprint("[ENV] Loading configuration...")
    base_env = load_env_chain(workspace_dir, component="claude")

    # ── GPU type from --cuda / --rocm flags ────────────────────────────────
    gpu_type: str | None = None
    if getattr(args, "gpu_cuda", False):
        gpu_type = "cuda"
    elif getattr(args, "gpu_rocm", False):
        gpu_type = "rocm"

    # ── Load profile ───────────────────────────────────────────────────────
    profile_name = args.profile or "default"
    profiles_path = resolve_profiles_path()

    profile_env: dict = {}
    sandbox_images: dict[str, str] = {}
    tools: list[str] = []
    mode = "sandbox" if args.sandbox else "local"
    if profiles_path.exists():
        try:
            profiles_dict = load_profiles(profiles_path)
            profile_env = load_profile_env(
                profile_name, profiles_path, base_env, mode, profiles=profiles_dict
            )
            sandbox_images = get_profile_sandbox_images(
                profile_name, profiles_path, profiles=profiles_dict
            )
            tools = get_profile_tools(
                profile_name, profiles_path, profiles=profiles_dict
            )
        except ProfileError as e:
            eprint(f"[ERROR] {e}")
            return 1
    elif profile_name != "default":
        eprint(
            f"[ERROR] Profile '{profile_name}' requested but no profiles file found."
        )
        return 1
    else:
        eprint("[PROFILE] No profiles file found. Using defaults only.")

    # ── Route execution ────────────────────────────────────────────────────
    if args.native_models:
        # Strip proxy-auth env vars so Claude Code uses its native /login auth
        _NATIVE_STRIP_VARS = {
            "ANTHROPIC_AUTH_TOKEN",
            "ANTHROPIC_BASE_URL",
            "IS_SANDBOX",
        }
        for var in _NATIVE_STRIP_VARS:
            if var in profile_env:
                eprint(
                    f"[NATIVE] Stripping '{var}' — using native Anthropic /login auth"
                )
                del profile_env[var]

    dangerously_skip = getattr(args, "dangerously_skip_permissions", False)
    run_as_me = getattr(args, "run_as_me", False)

    # ── Tools: ensure profile-declared tools are running ─────────────────
    # Tools are shared and persistent.  Start them if not already running.
    # They stay running until explicitly stopped via `cf tools stop`.
    session_id = generate_session_id(mode)
    acquired_tools: list[str] = []
    if tools:
        eprint(f"[TOOLS] Profile '{profile_name}' declares tools: {', '.join(tools)}")
        acquired_tools = acquire_tools(session_id, tools, profile_name)
        if acquired_tools:
            eprint(f"[TOOLS] Running: {', '.join(acquired_tools)}")

    try:
        if args.sandbox:
            # --run-as-me is only meaningful with --sandbox; silently ignore otherwise
            return run_docker(
                profile_env,
                args.claude_args,
                workspace_dir,
                profile_name,
                gpu_type=gpu_type,
                sandbox_images=sandbox_images,
                run_as_me=run_as_me,
                container_name=session_id,
                acquired_tools=acquired_tools,
            )
        else:
            if run_as_me:
                eprint("[WARN] --run-as-me is only valid with --sandbox; ignoring.")
            return run_local(profile_env, args.claude_args, dangerously_skip)
    finally:
        # release_tools is a no-op — tools persist until `cf tools stop`
        if acquired_tools:
            release_tools(session_id, acquired_tools)


