"""Code agent subcommand — launch with profile-based routing.

Usage:
    codefreedom run agent claude-code [--profile NAME] [--list-profiles] [agent-args...]
    codefreedom run agent claude-code [options] [-- <agent-args>]

VS Code integration: see `codefreedom setup config vscode`.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from codefreedom.config.runtime import list_profiles, resolve_agent_runtime
from codefreedom.core.config import resolve_profiles_path
from codefreedom.log import eprint, tag
from codefreedom.launcher import run_local
from codefreedom.tools.registry import generate_session_id


def register_args(parser: argparse.ArgumentParser) -> None:
    """Register Claude-specific arguments on the agent parser."""
    parser.add_argument(
        "--native-models",
        action="store_true",
        help="Use native Anthropic models/auth (/login)",
    )
    parser.add_argument(
        "--dangerously-skip-permissions",
        action="store_true",
        help="Skip Claude Code permission prompts (use in CI/non-interactive environments)",
    )


def init_claude() -> int:
    """Initialize Claude Code configuration via recipes.

    Bundled examples have been replaced by the recipe system.
    Use ``cf setup init`` or ``cf s i -p <name>`` instead.
    """
    from codefreedom.cli.docker_utils import print_help_section

    print_help_section(
        "claude init",
        [
            "Use:  cf s i <recipe-name>            # install a recipe",
            "      cf s i -l                      # list available recipes",
            "      cf s i -p <name>               # preview a recipe without applying",
            "      cf s i -pa <name>              # plan and apply a recipe",
        ],
        docs_url="https://nilayparikh.github.io/codefreedom/recipes/",
        include_disclaimer=True,
    )
    return 0


# VS Code settings generation moved to codefreedom.cli.vscode.


def cmd_config(args: argparse.Namespace) -> int:
    """Resolve profile env vars and print for standalone Claude Code use.

    Loads the full env chain (component-specific → shared → workspace →
    system), resolves the selected profile's env vars, and outputs them
    as source-able export statements (bash) or $env: assignments (PowerShell).

    Supports --out <file> for file output (recommended — values may include
    secrets), or stdout with interactive confirmation.
    """
    workspace_dir = Path.cwd()

    # ── Load env chain ─────────────────────────────────────────────────────
    eprint(f"{tag('ENV')} Loading configuration...")
    runtime = resolve_agent_runtime(
        "claude-code",
        workspace_dir=workspace_dir,
        profile_name=getattr(args, "profile", None) or "default",
        mode="local",
    )
    base_env = runtime.base_env

    # ── Load profile ───────────────────────────────────────────────────────
    profile_name = getattr(args, "profile", None) or "default"
    profiles_path = resolve_profiles_path()

    from codefreedom.cli.common import load_profile_env_only

    profile_env, exit_code = load_profile_env_only(
        profile_name,
        profiles_path,
        base_env,
        error_prefix="codefreedom run agent claude-code init",
        agent="claude-code",
    )
    if exit_code != 0:
        return 1

    # ── Determine format ────────────────────────────────────────────────────
    is_ps = getattr(args, "powershell", False)
    out_path = getattr(args, "out", None)

    # ── Build output ────────────────────────────────────────────────────────
    lines: list[str] = []
    if is_ps:
        lines.append("<#")
        lines.append("  Claude Code environment variables -- generated by codefreedom")
        lines.append(f"  Profile: {profile_name}")
        lines.append(
            "  WARNING: This file may contain sensitive values (API keys, tokens)."
        )
        lines.append("#>")
        lines.append("")
        for key in sorted(profile_env):
            val = profile_env[key]
            escaped = val.replace('"', '`"')
            lines.append(f'$env:{key} = "{escaped}"')
    else:
        lines.append("#!/usr/bin/env bash")
        lines.append("# Claude Code environment variables -- generated by codefreedom")
        lines.append(f"# Profile: {profile_name}")
        lines.append(
            "# WARNING: This file may contain sensitive values (API keys, tokens)."
        )
        lines.append("")
        for key in sorted(profile_env):
            val = profile_env[key]
            escaped = val.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'export {key}="{escaped}"')

    output = "\n".join(lines) + "\n"

    # ── Warning about secrets ───────────────────────────────────────────────
    warning = (
        "[CONFIG] WARNING: The generated output may contain sensitive values\n"
        "[CONFIG] (API keys, tokens, secrets). Review before sharing or committing.\n"
        "[CONFIG] Use --out <file> to write to a file for better security.\n"
    )

    if out_path:
        eprint(warning)
        from codefreedom.cli.common import write_output_file

        return write_output_file(output, out_path)

    # ── stdout path: warn and confirm ──────────────────────────────────────
    eprint(warning)
    from codefreedom.cli.common import confirm_stdout_output

    return confirm_stdout_output(output)


def run(args: argparse.Namespace) -> int:
    """Execute the claude subcommand. Returns exit code."""

    # Fast-path flags (no env loading needed)
    if args.list_profiles:
        from codefreedom.cli.common import display_profiles

        profiles_path = resolve_profiles_path()
        profiles = list_profiles(profiles_path, agent="claude-code")
        return display_profiles(profiles_path, profiles)

    # ── Load env chain ─────────────────────────────────────────────────────
    workspace_dir = Path.cwd()
    eprint(f"{tag('ENV')} Loading configuration...")

    # ── Load profile ───────────────────────────────────────────────────────
    profile_name = args.profile or "default"
    profiles_path = resolve_profiles_path()
    mode = "local"
    runtime = resolve_agent_runtime(
        "claude-code",
        workspace_dir=workspace_dir,
        profile_name=profile_name,
        mode=mode,
    )

    from codefreedom.cli.common import load_profile_with_tools

    profile_env, tools, exit_code = load_profile_with_tools(
        profile_name, profiles_path, runtime.base_env, mode,
        agent="claude-code",
    )
    if exit_code != 0:
        return 1

    # ── Route execution ────────────────────────────────────────────────────
    if args.native_models:
        # Strip proxy-auth env vars so Claude Code uses its native /login auth
        _NATIVE_STRIP_VARS = {
            "ANTHROPIC_AUTH_TOKEN",
            "ANTHROPIC_BASE_URL",
        }
        for var in _NATIVE_STRIP_VARS:
            if var in profile_env:
                eprint(
                    f"[NATIVE] Stripping '{var}' — using native Anthropic /login auth"
                )
                del profile_env[var]

    dangerously_skip = getattr(args, "dangerously_skip_permissions", False)

    # ── Tools: ensure profile-declared tools are running ─────────────────
    # Tools are shared and persistent.  Start them if not already running.
    # They stay running until explicitly stopped via `cf run tools stop`.
    session_id = generate_session_id(mode)

    from codefreedom.cli.common import acquire_and_run

    def _run(acquired_tools: list[str]) -> int:
        if acquired_tools:
            from codefreedom.launcher import _register_claude_mcp_servers

            _register_claude_mcp_servers(workspace_dir, acquired_tools)
        return run_local(profile_env, args.agent_args, dangerously_skip)

    return acquire_and_run(session_id, tools, profile_name, _run)
