"""Code agent subcommand — launch with profile-based routing and sandboxing.

Usage:
    codefreedom agent claude [--profile NAME] [--sandbox] [--list-profiles] [agent-args...]
    codefreedom agent claude [options] [-- <agent-args>]

VS Code integration: see `codefreedom config vscode`.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from codefreedom.config import resolve_profiles_path
from codefreedom.log import eprint
from codefreedom.env_loader import load_env_chain
from codefreedom.launcher import run_docker, run_local
from codefreedom.profiles import (
    list_profiles,
)
from codefreedom.tool_registry import generate_session_id


def register_args(parser: argparse.ArgumentParser) -> None:
    """Register Claude-specific arguments on the agent parser."""
    # GPU image flags (mutually exclusive, only meaningful with --sandbox)
    gpu_group = parser.add_mutually_exclusive_group()
    gpu_group.add_argument(
        "--cuda",
        action="store_true",
        dest="gpu_cuda",
        help="Use CUDA sandbox image for NVIDIA GPUs (only with --sandbox)",
    )
    gpu_group.add_argument(
        "--rocm",
        action="store_true",
        dest="gpu_rocm",
        help="Use ROCm sandbox image for AMD GPUs (only with --sandbox)",
    )

    parser.add_argument(
        "--sandbox",
        action="store_true",
        help="Run inside a sandboxed Docker container (default: native)",
    )
    parser.add_argument(
        "--run-as-me",
        action="store_true",
        help="Run sandbox container as host user (uid/gid match). Only valid with --sandbox.",
    )
    parser.add_argument(
        "--native-models",
        action="store_true",
        help="Use native Anthropic models/auth (/login)",
    )
    parser.add_argument(
        "--dangerously-skip-permissions",
        action="store_true",
        help="Skip Claude Code permission prompts (use in CI/non-interactive environments)",
    )


def init_claude() -> int:
    """Initialize Claude Code configuration via recipes.

    Bundled examples have been replaced by the recipe system.
    Use ``cf init`` or ``cf init --plan <name>`` instead.
    """
    from codefreedom.cli.docker_utils import print_help_section

    print_help_section(
        "claude init",
        [
            "Use:  cf init                    # install _default base recipe",
            "      cf init --list              # list available recipes",
            "      cf init --plan <name>       # preview a recipe without applying",
        ],
        docs_url="https://nilayparikh.github.io/codefreedom/recipes/",
        include_disclaimer=True,
    )
    return 0


# VS Code settings generation moved to codefreedom.cli.vscode.


def cmd_config(args: argparse.Namespace) -> int:
    """Resolve profile env vars and print for standalone Claude Code use.

    Loads the full env chain (component-specific → shared → workspace →
    system), resolves the selected profile's env vars, and outputs them
    as source-able export statements (bash) or $env: assignments (PowerShell).

    Supports --out <file> for file output (recommended — values may include
    secrets), or stdout with interactive confirmation.
    """
    workspace_dir = Path.cwd()

    # ── Load env chain ─────────────────────────────────────────────────────
    eprint("[ENV] Loading configuration...")
    base_env = load_env_chain(workspace_dir, component="claude")

    # ── Load profile ───────────────────────────────────────────────────────
    profile_name = getattr(args, "profile", None) or "default"
    profiles_path = resolve_profiles_path()

    from codefreedom.cli.common import load_profile_env_only

    profile_env, exit_code = load_profile_env_only(
        profile_name, profiles_path, base_env, error_prefix="codefreedom claude init"
    )
    if exit_code != 0:
        return 1

    # ── Determine format ────────────────────────────────────────────────────
    is_ps = getattr(args, "powershell", False)
    out_path = getattr(args, "out", None)

    # ── Build output ────────────────────────────────────────────────────────
    lines: list[str] = []
    if is_ps:
        lines.append("<#")
        lines.append("  Claude Code environment variables -- generated by codefreedom")
        lines.append(f"  Profile: {profile_name}")
        lines.append(
            "  WARNING: This file may contain sensitive values (API keys, tokens)."
        )
        lines.append("#>")
        lines.append("")
        for key in sorted(profile_env):
            val = profile_env[key]
            escaped = val.replace('"', '`"')
            lines.append(f'$env:{key} = "{escaped}"')
    else:
        lines.append("#!/usr/bin/env bash")
        lines.append("# Claude Code environment variables -- generated by codefreedom")
        lines.append(f"# Profile: {profile_name}")
        lines.append(
            "# WARNING: This file may contain sensitive values (API keys, tokens)."
        )
        lines.append("")
        for key in sorted(profile_env):
            val = profile_env[key]
            escaped = val.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'export {key}="{escaped}"')

    output = "\n".join(lines) + "\n"

    # ── Warning about secrets ───────────────────────────────────────────────
    warning = (
        "[CONFIG] WARNING: The generated output may contain sensitive values\n"
        "[CONFIG] (API keys, tokens, secrets). Review before sharing or committing.\n"
        "[CONFIG] Use --out <file> to write to a file for better security.\n"
    )

    if out_path:
        eprint(warning)
        from codefreedom.cli.common import write_output_file

        return write_output_file(output, out_path)

    # ── stdout path: warn and confirm ──────────────────────────────────────
    eprint(warning)
    from codefreedom.cli.common import confirm_stdout_output

    return confirm_stdout_output(output)


def run(args: argparse.Namespace) -> int:
    """Execute the claude subcommand. Returns exit code."""

    # Fast-path flags (no env loading needed)
    if args.list_profiles:
        from codefreedom.cli.common import display_profiles

        profiles_path = resolve_profiles_path()
        profiles = list_profiles(profiles_path)
        return display_profiles(profiles_path, profiles)

    # ── Load env chain ─────────────────────────────────────────────────────
    workspace_dir = Path.cwd()
    eprint("[ENV] Loading configuration...")
    base_env = load_env_chain(workspace_dir, component="claude")

    # ── GPU type from --cuda / --rocm flags ────────────────────────────────
    gpu_type: str | None = None
    if getattr(args, "gpu_cuda", False):
        gpu_type = "cuda"
    elif getattr(args, "gpu_rocm", False):
        gpu_type = "rocm"

    # ── Load profile ───────────────────────────────────────────────────────
    profile_name = args.profile or "default"
    profiles_path = resolve_profiles_path()
    mode = "sandbox" if args.sandbox else "local"

    from codefreedom.cli.common import load_profile_with_tools

    profile_env, sandbox_images, tools, exit_code = load_profile_with_tools(
        profile_name, profiles_path, base_env, mode
    )
    if exit_code != 0:
        return 1

    # ── Route execution ────────────────────────────────────────────────────
    if args.native_models:
        # Strip proxy-auth env vars so Claude Code uses its native /login auth
        _NATIVE_STRIP_VARS = {
            "ANTHROPIC_AUTH_TOKEN",
            "ANTHROPIC_BASE_URL",
            "IS_SANDBOX",
        }
        for var in _NATIVE_STRIP_VARS:
            if var in profile_env:
                eprint(
                    f"[NATIVE] Stripping '{var}' — using native Anthropic /login auth"
                )
                del profile_env[var]

    dangerously_skip = getattr(args, "dangerously_skip_permissions", False)
    run_as_me = getattr(args, "run_as_me", False)

    # ── Tools: ensure profile-declared tools are running ─────────────────
    # Tools are shared and persistent.  Start them if not already running.
    # They stay running until explicitly stopped via `cf tools stop`.
    session_id = generate_session_id(mode)

    from codefreedom.cli.common import acquire_and_run

    def _run() -> int:
        if args.sandbox:
            # --run-as-me is only meaningful with --sandbox; silently ignore otherwise
            return run_docker(
                profile_env,
                args.agent_args,
                workspace_dir,
                profile_name,
                gpu_type=gpu_type,
                sandbox_images=sandbox_images,
                run_as_me=run_as_me,
                container_name=session_id,
            )
        else:
            if run_as_me:
                eprint("[WARN] --run-as-me is only valid with --sandbox; ignoring.")
            return run_local(profile_env, args.agent_args, dangerously_skip)

    return acquire_and_run(session_id, tools, profile_name, _run)
