"""GitHub MCP Server tool — stdio↔HTTP bridge over ghcr.io/github/github-mcp-server.

Usage:
    codefreedom tools github init     Initialize tool profile (requires acceptance)
    codefreedom tools github start    Start GitHub MCP container (HTTP MCP on port 8082)
    codefreedom tools github stop     Stop and remove container
    codefreedom tools github restart  Restart container (preserves state)
    codefreedom tools github status   Show container status

The container runs a Python bridge that wraps github-mcp-server stdio with an
HTTP MCP endpoint on port 8082.  Coding agents connect via
http://127.0.0.1:8082/mcp just like the chrome and web tools.

Settings are loaded from ~/.codefreedom/profiles/github.json (generated by
'codefreedom tools github init').  See src/codefreedom/examples/tools/github/
for the template with all available options.
"""

from __future__ import annotations

import argparse
import json
import random
import socket
import subprocess
from pathlib import Path

from codefreedom.config import get_codefreedom_dir
from codefreedom.env_loader import eprint
from codefreedom.cli.docker_utils import (
    check_docker_available,
    container_exists,
    container_is_running,
    ensure_image,
    resolve_data_dir,
)
from codefreedom.cli.init_utils import copy_bundled_files, find_bundled_examples
from codefreedom.cli.tool_init_utils import (
    _print_non_disclaimer,
    _print_tool_notice,
    prompt_acceptance,
)

# ── Defaults ──────────────────────────────────────────────────────────────────

_DEFAULT_IMAGE = "docker.io/nilayparikh/codefreedom:github-latest"
_DEFAULT_CONTAINER_NAME = "codefreedom-tools-github"
_DEFAULT_PORT = 0  # 0 = auto-pick random free port

_CODEFREEDOM_DIR = get_codefreedom_dir()


def _default_data_dir() -> str:
    """Return the default data dir, respecting ``CODEFREEDOM_HOME``."""
    return str(get_codefreedom_dir() / "sandbox" / "tools" / "github")


# ── Random port helper ────────────────────────────────────────────────────────

_PORT_RANGE_START = 8100
_PORT_RANGE_END = 8199


def _find_free_port() -> int:
    """Find an unused TCP port in the configured range."""
    for _ in range(50):
        port = random.randint(_PORT_RANGE_START, _PORT_RANGE_END)
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            if s.connect_ex(("127.0.0.1", port)) != 0:
                return port
    # Fallback — let OS pick, localhost only
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _get_mapped_port(container_name: str) -> int | None:
    """Return the host port mapped to container port 8082 via docker port."""
    result = subprocess.run(
        ["docker", "port", container_name, "8082"],
        capture_output=True,
        text=True,
        timeout=5,
        check=False,
    )
    if result.returncode == 0 and result.stdout.strip():
        # Output: "0.0.0.0:8123" — extract port
        line = result.stdout.strip().split("\n")[0]
        if ":" in line:
            return int(line.rsplit(":", 1)[-1])
    return None


def _profile_path() -> Path:
    """Return the github tool profile path (re-evaluated each call so tests can
    override ``CODEFREEDOM_HOME`` after import)."""
    return get_codefreedom_dir() / "profiles" / "github.json"


# ── Profile loader ────────────────────────────────────────────────────────────


def _resolve_env_vars(env: dict) -> dict:
    """Resolve ``${VAR}`` and ``${VAR:-default}`` in string values.

    Uses ``os.environ`` for resolution.  Var references without a default
    expand to the environment value (or empty string if unset).
    """
    import os as _os
    import re as _re

    _VAR_RE = _re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)(?::-([^}]*))?\}")

    result = {}
    for key, val in env.items():
        if isinstance(val, str):

            def _expand(m: _re.Match) -> str:
                name = m.group(1)
                default_val = m.group(2)
                if name in _os.environ and _os.environ[name] != "":
                    return _os.environ[name]
                if default_val is not None:
                    return default_val
                return ""

            result[key] = _VAR_RE.sub(_expand, val)
        else:
            result[key] = val
    return result


def _load_profile() -> dict:
    """Load github tool profile from ~/.codefreedom/profiles/github.json.

    Returns a flat dict with keys: image, container_name, port, data_dir, env.
    Any missing key falls back to the hardcoded default above.
    """
    settings: dict = {
        "image": _DEFAULT_IMAGE,
        "container_name": _DEFAULT_CONTAINER_NAME,
        "port": _DEFAULT_PORT,
        "data_dir": _default_data_dir(),
        "env": {},
    }

    profile_path = _profile_path()
    if not profile_path.exists():
        return settings

    try:
        with open(profile_path, encoding="utf-8") as f:
            raw = json.load(f)
    except (json.JSONDecodeError, OSError) as exc:
        eprint(f"[GITHUB] Warning: failed to read {profile_path}: {exc}")
        return settings

    cfg = raw.get("github", {})
    if not isinstance(cfg, dict):
        return settings

    if isinstance(cfg.get("image"), str) and cfg["image"]:
        settings["image"] = cfg["image"]
    if isinstance(cfg.get("container_name"), str) and cfg["container_name"]:
        settings["container_name"] = cfg["container_name"]
    if isinstance(cfg.get("port"), int) and cfg["port"] >= 0:
        settings["port"] = cfg["port"]
    if isinstance(cfg.get("data_dir"), str) and cfg["data_dir"]:
        settings["data_dir"] = cfg["data_dir"]
    if isinstance(cfg.get("env"), dict):
        settings["env"] = _resolve_env_vars(cfg["env"])

    return settings


# ── Init ────────────────────────────────────────────────────────────────────


def init_tool() -> int:
    """Initialize the github tool profile from bundled examples.

    Only copies files into an empty target -- if profile already exists,
    directs user to docs and example configs for manual merging.

    Requires user acceptance of third-party components.
    """
    if not prompt_acceptance("github"):
        return 1

    bundled = find_bundled_examples(__file__)
    tools_src = bundled / "tools" / "github"
    profiles_dst_dir = _CODEFREEDOM_DIR / "profiles"

    created = copy_bundled_files(
        tools_src,
        profiles_dst_dir,
        label="github init",
        docs_url="https://nilayparikh.github.io/codefreedom/tools/github/",
        examples_url="https://github.com/nilayparikh/codefreedom/tree/main/src/codefreedom/examples/tools/github/",
    )

    print()
    if created:
        print(f"[github init] Done -- {len(created)} created.")
    _print_non_disclaimer()
    return 0


# ── Actions ────────────────────────────────────────────────────────────────────


def start(settings: dict) -> int:
    """Start the GitHub MCP container. Returns exit code."""
    # ── Init gate: refuse to start if tool not initialized ───────────────
    profile_path = _profile_path()
    if not profile_path.exists():
        eprint("[github] Tool not initialized.")
        eprint("         Run:  codefreedom tools github init")
        eprint("         Docs: https://nilayparikh.github.io/codefreedom/tools/github/")
        return 1

    # ── Third-party notice on every start ────────────────────────────────
    _print_tool_notice("github")

    image = settings["image"]
    container_name = settings["container_name"]
    data_dir = settings["data_dir"]
    env_vars = dict(settings.get("env", {}))

    # Validate required token
    token = env_vars.get("GITHUB_PERSONAL_ACCESS_TOKEN", "")
    if not token:
        eprint("[ERROR] GITHUB_PERSONAL_ACCESS_TOKEN is not set.")
        eprint("   Set it in ~/.codefreedom/profiles/github.json under env:")
        eprint('     "env": { "GITHUB_PERSONAL_ACCESS_TOKEN": "ghp_..." }')
        return 1

    if container_is_running(container_name):
        port = _get_mapped_port(container_name) or settings["port"]
        eprint(f"[GITHUB] Container '{container_name}' is already running.")
        eprint(f"[GITHUB]   MCP endpoint: http://127.0.0.1:{port}/mcp")
        return 0

    # Check if Docker is available
    if not check_docker_available():
        eprint("[ERROR] Docker not found. Install Docker and try again.")
        return 1

    # Resolve & create data directory
    resolved_data = resolve_data_dir(data_dir)
    eprint(f"[GITHUB] Using data dir: {resolved_data}")

    # Remove existing container if stopped
    if container_exists(container_name):
        eprint(f"[GITHUB] Removing existing container '{container_name}'...")
        subprocess.run(
            ["docker", "rm", "-f", container_name],
            capture_output=True,
            timeout=15,
            check=False,
        )

    # Ensure image is available
    if not ensure_image(
        image,
        label="GITHUB",
        build_tip="docker build -t codefreedom:github -f docker/github/Dockerfile.Github docker/github/",
        profile_path="~/.codefreedom/profiles/github.json",
    ):
        return 1

    # Pick port: use explicit setting, or auto-pick from random range
    host_port = settings["port"]
    if host_port == 0:
        host_port = _find_free_port()

    # Build environment flags
    env_flags: list[str] = []
    for key, val in env_vars.items():
        env_flags.extend(["-e", f"{key}={val}"])

    eprint(f"[GITHUB] Starting container '{container_name}'...")
    eprint(f"[GITHUB]   HTTP MCP port: {host_port}")
    create = subprocess.run(
        [
            "docker",
            "run",
            "-d",
            "--name",
            container_name,
            "--restart",
            "unless-stopped",
            "-p",
            f"127.0.0.1:{host_port}:8082",
            "-v",
            f"{resolved_data}:/data",
            *env_flags,
            image,
        ],
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    if create.returncode != 0:
        eprint("[ERROR] Failed to start GitHub MCP container.")
        if create.stderr:
            eprint(f"   {create.stderr.strip()}")
        return 1

    eprint("   [OK] Container started.")
    eprint(f"   MCP endpoint: http://127.0.0.1:{host_port}/mcp")
    return 0


def stop(settings: dict) -> int:
    """Stop and remove the GitHub MCP container. Returns exit code."""
    container_name = settings["container_name"]

    if not container_exists(container_name):
        eprint(f"[GITHUB] Container '{container_name}' does not exist.")
        return 0

    eprint(f"[GITHUB] Stopping container '{container_name}'...")
    subprocess.run(
        ["docker", "stop", container_name],
        capture_output=True,
        timeout=30,
        check=False,
    )
    subprocess.run(
        ["docker", "rm", container_name],
        capture_output=True,
        timeout=15,
        check=False,
    )
    eprint("   [OK] Container stopped and removed.")
    return 0


def restart(settings: dict) -> int:
    """Restart the GitHub MCP container using `docker restart`.

    Preserves the container ID, logs, and network namespace. Does NOT pull
    a new image — to pick up a new image tag, use `stop` then `start`.
    """
    container_name = settings["container_name"]

    if not container_exists(container_name):
        eprint(f"[GITHUB] Container '{container_name}' does not exist.")
        eprint("   Start one with:  codefreedom tools github start")
        return 1

    eprint(f"[GITHUB] Restarting container '{container_name}'...")
    result = subprocess.run(
        ["docker", "restart", container_name],
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )
    if result.returncode != 0:
        eprint("[ERROR] Failed to restart GitHub MCP container.")
        if result.stderr:
            eprint(f"   {result.stderr.strip()}")
        return 1

    port = _get_mapped_port(container_name) or "?"
    eprint("   [OK] Container restarted.")
    eprint(f"   MCP endpoint: http://127.0.0.1:{port}/mcp")
    return 0


def status(settings: dict) -> int:
    """Show GitHub MCP container status. Returns exit code."""
    container_name = settings["container_name"]

    if container_is_running(container_name):
        port = _get_mapped_port(container_name) or "?"
        eprint(f"[GITHUB] Container '{container_name}' is running.")
        eprint(f"[GITHUB] MCP endpoint: http://127.0.0.1:{port}/mcp")
        eprint("[GITHUB] Tools: GitHub API operations (issues, PRs, repos, etc.)")
        return 0

    if container_exists(container_name):
        eprint(f"[GITHUB] Container '{container_name}' exists but is not running.")
        return 1

    eprint("[GITHUB] No GitHub MCP container found.")
    eprint("   Start with: codefreedom tools github start")
    return 1


# ── Entry point ──────────────────────────────────────────────────────────


def run(args: argparse.Namespace) -> int:
    settings = _load_profile()

    # Override port from CLI if specified
    if getattr(args, "port", None) and args.port != _DEFAULT_PORT:
        settings["port"] = args.port

    if args.action == "start":
        return start(settings)
    elif args.action == "stop":
        return stop(settings)
    elif args.action == "restart":
        return restart(settings)
    elif args.action == "status":
        return status(settings)
    else:
        eprint(f"[ERROR] Unknown action: {args.action}")
        return 1
