"""Camoufox web search tool — run Camoufox in Docker for stealth web search/scraping.

Usage:
    codefreedom tools web init     Initialize tool profile (requires acceptance)
    codefreedom tools web start    Start Camoufox container (MCP server on port 8420)
    codefreedom tools web stop     Stop and remove Camoufox container
    codefreedom tools web status   Show Camoufox container status

The container runs an MCP-only server with two tools:
    web_search(query) — search Brave + Bing
    web_fetch(url)    — fetch a page (bypasses anti-bot)

Settings are loaded from ~/.codefreedom/profiles/camoufox.json (generated by
'codefreedom tools web init').  See src/codefreedom/examples/tools/web/
for the template with all available options.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path

from codefreedom.env_loader import eprint
from codefreedom.cli.tool_init_utils import (
    _print_non_disclaimer,
    _print_tool_notice,
    prompt_acceptance,
)

# ── Defaults ─────────────────────────────────────────────────────────────

_DEFAULT_IMAGE = "codefreedom:camoufox"
_DEFAULT_CONTAINER_NAME = "codefreedom-camoufox"
_DEFAULT_PORT = 8420
_DEFAULT_DATA_DIR = "~/.codefreedom/sandbox/tools/camoufox"

_CODEFREEDOM_DIR = Path.home() / ".codefreedom"
_PROFILE_PATH = _CODEFREEDOM_DIR / "profiles" / "camoufox.json"


# ── Profile loader ───────────────────────────────────────────────────────


def _load_profile() -> dict:
    """Load camoufox tool profile from ~/.codefreedom/profiles/camoufox.json.

    Returns a flat dict with keys: image, container_name, port, data_dir, env.
    Any missing key falls back to the hardcoded default above.
    """
    settings: dict = {
        "image": _DEFAULT_IMAGE,
        "container_name": _DEFAULT_CONTAINER_NAME,
        "port": _DEFAULT_PORT,
        "data_dir": _DEFAULT_DATA_DIR,
        "env": {},
    }

    if not _PROFILE_PATH.exists():
        return settings

    try:
        with open(_PROFILE_PATH, encoding="utf-8") as f:
            raw = json.load(f)
    except (json.JSONDecodeError, OSError) as exc:
        eprint(f"[WEB] Warning: failed to read {_PROFILE_PATH}: {exc}")
        return settings

    cfg = raw.get("camoufox", {})
    if not isinstance(cfg, dict):
        return settings

    if isinstance(cfg.get("image"), str) and cfg["image"]:
        settings["image"] = cfg["image"]
    if isinstance(cfg.get("container_name"), str) and cfg["container_name"]:
        settings["container_name"] = cfg["container_name"]
    if isinstance(cfg.get("port"), int) and cfg["port"] > 0:
        settings["port"] = cfg["port"]
    if isinstance(cfg.get("data_dir"), str) and cfg["data_dir"]:
        settings["data_dir"] = cfg["data_dir"]
    if isinstance(cfg.get("env"), dict):
        settings["env"] = cfg["env"]

    return settings


# ── Helpers ──────────────────────────────────────────────────────────────


def _resolve_data_dir(data_dir: str) -> Path:
    path = Path(data_dir).expanduser()
    path.mkdir(parents=True, exist_ok=True)
    return path


def _container_exists(name: str) -> bool:
    try:
        result = subprocess.run(
            [
                "docker",
                "ps",
                "-a",
                "--filter",
                f"name={name}",
                "--format",
                "{{.Names}}",
            ],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
        return name in result.stdout.strip().split("\n")
    except (subprocess.SubprocessError, FileNotFoundError):
        return False


def _container_is_running(name: str) -> bool:
    try:
        result = subprocess.run(
            ["docker", "ps", "--filter", f"name={name}", "--format", "{{.Names}}"],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
        return name in result.stdout.strip().split("\n")
    except (subprocess.SubprocessError, FileNotFoundError):
        return False


def _ensure_image(image: str) -> bool:
    _inspect = subprocess.run(
        ["docker", "image", "inspect", image],
        capture_output=True,
        text=True,
        timeout=10,
        check=False,
    )
    if _inspect.returncode == 0:
        eprint(f"[WEB] Using cached image '{image}'")
        return True

    eprint(f"[WEB] Image '{image}' not found locally, pulling...")
    pull = subprocess.run(
        ["docker", "pull", image],
        capture_output=True,
        text=True,
        timeout=120,
        check=False,
    )
    if pull.returncode == 0:
        eprint("   [OK] Image pulled.")
        return True

    eprint(f"[ERROR] Failed to pull image '{image}'.")
    if pull.stderr:
        eprint(f"   {pull.stderr.strip()}")
    eprint("")
    eprint("  Tips:")
    eprint(
        "    • Build locally:  docker build -t codefreedom:camoufox -f docker/camoufox/Dockerfile.Camoufox docker/camoufox/"
    )
    eprint(
        "    • Set 'image' in ~/.codefreedom/profiles/camoufox.json to your local tag"
    )
    eprint("    • Wait for CI to publish the image to ghcr.io")
    return False


# ── Init ────────────────────────────────────────────────────────────────────


def _find_bundled_examples() -> Path:
    """Find the bundled examples directory inside the installed package."""
    return Path(__file__).resolve().parent.parent / "examples"


def init_tool(reset: bool = False) -> int:
    """Initialize the web/camoufox tool profile from bundled examples.

    Requires user acceptance of third-party components.
    """
    if not prompt_acceptance("web"):
        return 1

    bundled = _find_bundled_examples()
    tools_src = bundled / "tools" / "web"
    profiles_dst_dir = _CODEFREEDOM_DIR / "profiles"

    created: list[str] = []

    def _copy(src: Path, dst: Path) -> None:
        if not reset and dst.exists():
            print(f"[web init] [SKIP] Already exists: {dst}")
        elif src.exists():
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
            created.append(str(dst))
            print(f"[web init] [OK]   Created {dst}")
        else:
            print(f"[web init] [FAIL] Source not found: {src}")

    _copy(tools_src / "camoufox.json", profiles_dst_dir / "camoufox.json")
    _copy(tools_src / "camoufox.schema.json", profiles_dst_dir / "camoufox.schema.json")

    print()
    if created:
        print(f"[web init] Done — {len(created)} created.")
    else:
        print("[web init] Nothing to do — already exists.")
        print("           Use --reset to overwrite.")
    print(
        "           Docs: https://nilayparikh.github.io/codefreedom/claude-code/tools/"
    )
    _print_non_disclaimer()
    return 0


# ── Actions ──────────────────────────────────────────────────────────────


def start(settings: dict) -> int:
    # ── Init gate: refuse to start if tool not initialized ───────────────
    if not _PROFILE_PATH.exists():
        eprint("[web] Tool not initialized.")
        eprint("      Run:  codefreedom tools web init")
        eprint(
            "      Docs: https://nilayparikh.github.io/codefreedom/claude-code/tools/"
        )
        return 1

    # ── Third-party notice on every start ────────────────────────────────
    _print_tool_notice("web")

    image = settings["image"]
    container_name = settings["container_name"]
    port = settings["port"]
    data_dir = settings["data_dir"]

    if _container_is_running(container_name):
        eprint(f"[WEB] Container '{container_name}' is already running.")
        return 0

    if (
        subprocess.run(
            ["docker", "--version"], capture_output=True, timeout=5, check=False
        ).returncode
        != 0
    ):
        eprint("[ERROR] Docker not found. Install Docker and try again.")
        return 1

    resolved_data = _resolve_data_dir(data_dir)
    eprint(f"[WEB] Using data dir: {resolved_data}")

    if _container_exists(container_name):
        subprocess.run(
            ["docker", "rm", "-f", container_name],
            capture_output=True,
            timeout=10,
            check=False,
        )

    if not _ensure_image(image):
        return 1

    eprint(f"[WEB] Starting container '{container_name}'...")
    result = subprocess.run(
        [
            "docker",
            "run",
            "-d",
            "--name",
            container_name,
            "--restart",
            "unless-stopped",
            "-p",
            f"{port}:8420",
            "-v",
            f"{resolved_data}:/userdata",
            image,
        ],
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )

    if result.returncode != 0:
        eprint(f"[ERROR] Failed to start container: {result.stderr.strip()}")
        return 1

    eprint(f"[WEB] Container started: {result.stdout.strip()[:12]}")
    eprint(f"[WEB] MCP endpoint: http://127.0.0.1:{port}/mcp")
    return 0


def stop(settings: dict) -> int:
    container_name = settings["container_name"]
    if not _container_exists(container_name):
        eprint(f"[WEB] Container '{container_name}' not found.")
        return 0

    eprint(f"[WEB] Stopping container '{container_name}'...")
    subprocess.run(
        ["docker", "stop", container_name], capture_output=True, timeout=30, check=False
    )
    subprocess.run(
        ["docker", "rm", container_name], capture_output=True, timeout=10, check=False
    )
    eprint("[WEB] Container stopped.")
    return 0


def status(settings: dict) -> int:
    container_name = settings["container_name"]
    port = settings["port"]

    if _container_is_running(container_name):
        eprint(f"[WEB] Container '{container_name}' is running.")
        eprint(f"[WEB] MCP endpoint: http://127.0.0.1:{port}/mcp")
        eprint("[WEB] Tools: web_search, web_fetch")
        return 0

    if _container_exists(container_name):
        eprint(f"[WEB] Container '{container_name}' exists but is not running.")
        return 1

    eprint("[WEB] No Camoufox container found.")
    eprint("   Start with: codefreedom tools web start")
    return 1


# ── Entry point ──────────────────────────────────────────────────────────


def run(args: argparse.Namespace) -> int:
    settings = _load_profile()

    # Override port from CLI if specified
    if getattr(args, "port", None) and args.port != _DEFAULT_PORT:
        settings["port"] = args.port

    if args.action == "start":
        return start(settings)
    elif args.action == "stop":
        return stop(settings)
    elif args.action == "status":
        return status(settings)
    else:
        eprint(f"[ERROR] Unknown action: {args.action}")
        return 1
