"""Camoufox web search tool — run Camoufox in Docker for stealth web search/scraping.

Usage:
    codefreedom tools web init     Initialize tool profile (requires acceptance)
    codefreedom tools web start    Start Camoufox container (MCP server on port 8420)
    codefreedom tools web stop     Stop and remove Camoufox container
    codefreedom tools web status   Show Camoufox container status

The container runs an MCP-only server with two tools:
    web_search(query) — search configured engines
    web_fetch(url)    — fetch a page (bypasses anti-bot)

Settings are loaded from ~/.codefreedom/profiles/camoufox.json (generated by
'codefreedom tools web init').  See src/codefreedom/examples/tools/web/
for the template with all available options.

Search engines are configured in the profile's 'search_engines' field
(each entry: {url, parser}) and passed to the container as the SEARCH_ENGINES
environment variable (JSON-serialized).
"""

from __future__ import annotations

import argparse
import json
import subprocess

from codefreedom.config import get_codefreedom_dir
from codefreedom.env_loader import eprint
from codefreedom.cli.docker_utils import (
    check_docker_available,
    container_exists,
    container_is_running,
    ensure_image,
    resolve_data_dir,
)
from codefreedom.cli.init_utils import copy_bundled_files, find_bundled_examples
from codefreedom.cli.tool_init_utils import (
    _print_non_disclaimer,
    _print_tool_notice,
    prompt_acceptance,
)

# ── Defaults ─────────────────────────────────────────────────────────────

_DEFAULT_IMAGE = "codefreedom:camoufox"
_DEFAULT_CONTAINER_NAME = "codefreedom-camoufox"
_DEFAULT_PORT = 8420
_DEFAULT_DATA_DIR = "~/.codefreedom/sandbox/tools/camoufox"

_CODEFREEDOM_DIR = get_codefreedom_dir()
_PROFILE_PATH = _CODEFREEDOM_DIR / "profiles" / "camoufox.json"


# ── Profile loader ───────────────────────────────────────────────────────


def _load_profile() -> dict:
    """Load camoufox tool profile from ~/.codefreedom/profiles/camoufox.json.

    Returns a flat dict with keys: image, container_name, port, data_dir, env,
    search_engines, parser_registry.
    Any missing key falls back to the hardcoded default above.
    """
    settings: dict = {
        "image": _DEFAULT_IMAGE,
        "container_name": _DEFAULT_CONTAINER_NAME,
        "port": _DEFAULT_PORT,
        "data_dir": _DEFAULT_DATA_DIR,
        "env": {},
        "search_engines": {},
        "parser_registry": {},
    }

    if not _PROFILE_PATH.exists():
        return settings

    try:
        with open(_PROFILE_PATH, encoding="utf-8") as f:
            raw = json.load(f)
    except (json.JSONDecodeError, OSError) as exc:
        eprint(f"[WEB] Warning: failed to read {_PROFILE_PATH}: {exc}")
        return settings

    cfg = raw.get("camoufox", {})
    if not isinstance(cfg, dict):
        return settings

    if isinstance(cfg.get("image"), str) and cfg["image"]:
        settings["image"] = cfg["image"]
    if isinstance(cfg.get("container_name"), str) and cfg["container_name"]:
        settings["container_name"] = cfg["container_name"]
    if isinstance(cfg.get("port"), int) and cfg["port"] > 0:
        settings["port"] = cfg["port"]
    if isinstance(cfg.get("data_dir"), str) and cfg["data_dir"]:
        settings["data_dir"] = cfg["data_dir"]
    if isinstance(cfg.get("env"), dict):
        settings["env"] = cfg["env"]
    if isinstance(cfg.get("search_engines"), dict):
        settings["search_engines"] = cfg["search_engines"]
    if isinstance(cfg.get("parser_registry"), dict):
        settings["parser_registry"] = cfg["parser_registry"]

    return settings


# ── Init ────────────────────────────────────────────────────────────────────


def init_tool() -> int:
    """Initialize the web/camoufox tool profile from bundled examples.

    Only copies files into an empty target — if profile already exists,
    directs user to docs and example configs for manual merging.

    Requires user acceptance of third-party components.
    """
    if not prompt_acceptance("web"):
        return 1

    bundled = find_bundled_examples(__file__)
    tools_src = bundled / "tools" / "web"
    profiles_dst_dir = _CODEFREEDOM_DIR / "profiles"

    created = copy_bundled_files(
        tools_src,
        profiles_dst_dir,
        label="web init",
        docs_url="https://nilayparikh.github.io/codefreedom/tools/web/",
        examples_url="https://github.com/nilayparikh/codefreedom/tree/main/src/codefreedom/examples/tools/web/",
    )

    print()
    if created:
        print(f"[web init] Done — {len(created)} created.")
    _print_non_disclaimer()
    return 0


# ── Actions ──────────────────────────────────────────────────────────────


def start(settings: dict) -> int:
    # ── Init gate: refuse to start if tool not initialized ───────────────
    if not _PROFILE_PATH.exists():
        eprint("[web] Tool not initialized.")
        eprint("      Run:  codefreedom tools web init")
        eprint(
            "      Docs: https://nilayparikh.github.io/codefreedom/claude-code/tools/"
        )
        return 1

    # ── Third-party notice on every start ────────────────────────────────
    _print_tool_notice("web")

    image = settings["image"]
    container_name = settings["container_name"]
    port = settings["port"]
    data_dir = settings["data_dir"]

    if container_is_running(container_name):
        eprint(f"[WEB] Container '{container_name}' is already running.")
        return 0

    if not check_docker_available():
        eprint("[ERROR] Docker not found. Install Docker and try again.")
        return 1

    resolved_data = resolve_data_dir(data_dir)
    eprint(f"[WEB] Using data dir: {resolved_data}")

    if container_exists(container_name):
        subprocess.run(
            ["docker", "rm", "-f", container_name],
            capture_output=True,
            timeout=10,
            check=False,
        )

    if not ensure_image(
        image,
        label="WEB",
        build_tip="docker build -t codefreedom:camoufox -f docker/web/Dockerfile.Camoufox docker/web/",
        profile_path="~/.codefreedom/profiles/camoufox.json",
    ):
        return 1

    # Build environment flags from profile
    env_vars = dict(settings.get("env", {}))
    # Serialize search_engines as SEARCH_ENGINES env var for the container
    search_engines = settings.get("search_engines", {})
    if isinstance(search_engines, dict) and search_engines:
        env_vars["SEARCH_ENGINES"] = json.dumps(search_engines)
    # Serialize parser_registry as PARSER_REGISTRY env var for the container
    parser_registry = settings.get("parser_registry", {})
    if isinstance(parser_registry, dict) and parser_registry:
        env_vars["PARSER_REGISTRY"] = json.dumps(parser_registry)
    env_flags: list[str] = []
    for key, val in env_vars.items():
        env_flags.extend(["-e", f"{key}={val}"])

    eprint(f"[WEB] Starting container '{container_name}'...")
    result = subprocess.run(
        [
            "docker",
            "run",
            "-d",
            "--name",
            container_name,
            "--restart",
            "unless-stopped",
            "-p",
            f"{port}:8420",
            "-v",
            f"{resolved_data}:/userdata",
            *env_flags,
            image,
        ],
        capture_output=True,
        text=True,
        timeout=30,
        check=False,
    )

    if result.returncode != 0:
        eprint(f"[ERROR] Failed to start container: {result.stderr.strip()}")
        return 1

    eprint(f"[WEB] Container started: {result.stdout.strip()[:12]}")
    eprint(f"[WEB] MCP endpoint: http://127.0.0.1:{port}/mcp")
    return 0


def stop(settings: dict) -> int:
    container_name = settings["container_name"]
    if not container_exists(container_name):
        eprint(f"[WEB] Container '{container_name}' not found.")
        return 0

    eprint(f"[WEB] Stopping container '{container_name}'...")
    subprocess.run(
        ["docker", "stop", container_name], capture_output=True, timeout=30, check=False
    )
    subprocess.run(
        ["docker", "rm", container_name], capture_output=True, timeout=10, check=False
    )
    eprint("[WEB] Container stopped.")
    return 0


def status(settings: dict) -> int:
    container_name = settings["container_name"]
    port = settings["port"]

    if container_is_running(container_name):
        eprint(f"[WEB] Container '{container_name}' is running.")
        eprint(f"[WEB] MCP endpoint: http://127.0.0.1:{port}/mcp")
        eprint("[WEB] Tools: web_search, web_fetch")
        return 0

    if container_exists(container_name):
        eprint(f"[WEB] Container '{container_name}' exists but is not running.")
        return 1

    eprint("[WEB] No Camoufox container found.")
    eprint("   Start with: codefreedom tools web start")
    return 1


# ── Entry point ──────────────────────────────────────────────────────────


def run(args: argparse.Namespace) -> int:
    settings = _load_profile()

    # Override port from CLI if specified
    if getattr(args, "port", None) and args.port != _DEFAULT_PORT:
        settings["port"] = args.port

    if args.action == "start":
        return start(settings)
    elif args.action == "stop":
        return stop(settings)
    elif args.action == "status":
        return status(settings)
    else:
        eprint(f"[ERROR] Unknown action: {args.action}")
        return 1
