"""cf git pr — PR generation and creation workflow."""

from __future__ import annotations

import re
import shutil
import subprocess
import urllib.parse
from pathlib import Path

from codefreedom.cli.git import git_ops, llm
from codefreedom.cli.git.config import (
    get_model,
    get_modules,
    get_template,
    load_git_config,
)
from codefreedom.cli.git.specs import PULL_REQUEST_GUIDE
from codefreedom.log import eprint, tag

_PR_TITLE_TYPE_RE = re.compile(
    r"^\s*(feat|fix|chore|docs|style|refactor|perf|test|build|ci|revert)"
    r"(?:\(([a-zA-Z0-9_\-/]+)\))?\s*:",
)
_BODY_SECTION_RE = re.compile(r"^##\s+\S+", re.MULTILINE)
_MAX_RETRIES = 2
_RETRY_PREVIEW_CHARS = 320


def _build_pr_system_prompt(
    config: dict,
    template: str,
) -> str:
    """Build the system prompt for PR generation.

    Bundles the full PR guide inline as a "skill" so the model has
    the reference available without URL lookups.
    """
    modules = get_modules(config)

    parts: list[str] = [
        "You are a pull request description generator.",
        "Apply the Pull Request Guide that follows INLINE — do NOT visit "
        "any URL; the spec is provided below.",
        "",
    ]

    parts.append(PULL_REQUEST_GUIDE)
    parts.append("")

    if modules:
        parts.extend([
            "## Available scopes (for this project)",
            ", ".join(modules),
            "Pick the most relevant scope in the title. Lowercase only.",
            "",
        ])
    else:
        parts.extend([
            "## Scope",
            "Infer a short lowercase scope from the changed files. Omit "
            "the scope if nothing fits cleanly.",
            "",
        ])

    parts.extend([
        "## PR body template to fill in",
        template.strip() or "(no template — use the structure from the guide above)",
        "",
        "## Strict output rules for this task",
        "- Output MUST follow this exact two-block format:",
        "    TITLE: <conventional commit title>",
        "    BODY:",
        "    <body using the template above, indented 4 spaces or not>",
        "- TITLE is ONE single line, no quotes, no backticks.",
        "- BODY starts on the line right after the `BODY:` line; never put "
        "the body on the same line as `BODY:`.",
        "- Do NOT include `` blocks, reasoning, or chain-of-thought "
        "in your final output.",
        "- Do NOT include role tags like [user] or [assistant].",
        "- Do NOT add a \"Generated by ...\" footer.",
        "- Do NOT prefix the title with \"TITLE:\" inside a code fence or "
        "quote — emit it as the first line of your reply.",
    ])

    return "\n".join(parts)


def _validate_pr_response(
    title: str,
    body: str,
) -> tuple[str, str, str | None]:
    """Validate a PR title/body pair.

    Returns ``(title, body, None)`` on success, or
    ``(title, body, error_reason)`` on failure.
    """
    if not title or not title.strip():
        return title, body, "TITLE is empty."

    title = title.strip()
    first_line = title.split("\n", 1)[0].strip()

    m = _PR_TITLE_TYPE_RE.match(first_line)
    if not m:
        return title, body, (
            f"TITLE does not start with a valid Conventional Commits type. "
            f"Got: {first_line!r}. Expected format: "
            "TYPE(SCOPE): DESCRIPTION."
        )

    commit_type = m.group(1)
    scope = m.group(2) or ""
    prefix = f"{commit_type}({scope})" if scope else commit_type

    description = first_line[m.end():].strip()
    if not description:
        return title, body, (
            f"TITLE description is empty after '{prefix}:'."
        )

    if len(first_line) > 72:
        return title, body, (
            f"TITLE is {len(first_line)} chars; keep it under 72."
        )

    if not body or not body.strip():
        return title, body, "BODY is empty."

    body = body.strip()
    if len(body) < 40:
        return title, body, (
            f"BODY is too short ({len(body)} chars); use the Summary, "
            "Changes, and Testing sections from the inline guide."
        )

    if not _BODY_SECTION_RE.search(body):
        return title, body, (
            "BODY has no '## Section' heading. Include at least one of: "
            "## Summary, ## Changes, ## Testing, ## Related issues."
        )

    return title, body, None


def _build_pr_retry_user_prompt(
    previous_response: str,
    error_reason: str,
    original_user_prompt: str,
) -> str:
    """Build the user prompt sent on a PR retry attempt."""
    preview = previous_response.strip()
    if len(preview) > _RETRY_PREVIEW_CHARS:
        preview = preview[:_RETRY_PREVIEW_CHARS] + "..."
    safe_preview = preview if preview else "<empty response>"

    return (
        "Your previous response did not match the required PR format.\n\n"
        "## Your previous response (verbatim)\n"
        f"```\n{safe_preview}\n```\n\n"
        "## Why it failed\n"
        f"{error_reason}\n\n"
        "## How to fix\n"
        "Reply with EXACTLY two blocks:\n"
        "  TITLE: <TYPE(SCOPE): DESCRIPTION>  (one line)\n"
        "  BODY:\n"
        "  <body with ## Summary, ## Changes, ## Testing sections>\n\n"
        "## Example of a correct response\n"
        "TITLE: feat(auth): add OAuth2 login support\n"
        "BODY:\n"
        "## Summary\n"
        "Adds OAuth2 login so users can sign in with Google.\n\n"
        "## Changes\n"
        "- Add /api/v1/auth/oauth/google endpoint\n"
        "- Add OAuthConfig model in config/auth.py\n\n"
        "## Testing\n"
        "- Add unit tests for OAuthConfig\n"
        "- Manual test: complete login flow\n\n"
        "## Original task\n"
        f"{original_user_prompt}"
    )


def _prompt_user(message: str, default: str = "y") -> str:
    """Prompt the user for confirmation. Returns 'y' or 'n'."""
    hint = "Y/n" if default == "y" else "y/N"
    try:
        response = input(f"\n{message} [{hint}]: ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        return "n"
    if not response:
        return default
    return response[0]


def _open_browser(url: str) -> bool:
    """Open a URL in the default browser."""
    import webbrowser
    try:
        webbrowser.open(url)
        return True
    except Exception as e:
        eprint(f"{tag('ERROR')} Failed to open browser: {e}")
        return False


def _gh_available() -> bool:
    """Check if gh CLI is installed."""
    return shutil.which("gh") is not None


def _create_pr_gh(
    source: str, target: str, title: str, body: str, cwd: Path
) -> tuple[bool, str]:
    """Create a PR via gh CLI."""
    result = subprocess.run(
        [
            "gh", "pr", "create",
            "--base", target,
            "--head", source,
            "--title", title,
            "--body", body,
        ],
        capture_output=True,
        text=True,
        timeout=30,
        cwd=str(cwd),
    )
    return result.returncode == 0, result.stdout + result.stderr


def _generate_pr_message(
    model: str,
    system_prompt: str,
    user_prompt: str,
    work_dir: Path,
) -> tuple[str, str, int]:
    """Generate a PR title/body with retries on validation failure.

    Returns ``(title, body, exit_code)``. exit_code != 0 means bail early.
    """
    eprint(f"{tag('PR')} Generating PR description via {model}...")

    original_user_prompt = user_prompt

    for attempt in range(_MAX_RETRIES + 1):
        response = llm.generate_message(
            model,
            system_prompt,
            user_prompt,
            max_tokens=16000,
            work_dir=work_dir,
        )
        if response is None:
            return "", "", 1

        parsed = llm.parse_pr_response(response)
        title = parsed["title"]
        body = parsed["body"]

        validated_title, validated_body, error_reason = _validate_pr_response(
            title, body
        )
        if error_reason is None:
            return validated_title, validated_body, -1

        if attempt < _MAX_RETRIES:
            preview = response.strip()
            if len(preview) > _RETRY_PREVIEW_CHARS:
                preview = preview[:_RETRY_PREVIEW_CHARS] + "..."
            preview = preview if preview else "<empty>"
            eprint(
                f"{tag('WARN')} Malformed PR description "
                f"(attempt {attempt + 1}/{_MAX_RETRIES + 1}), retrying..."
            )
            eprint(f"   LLM returned: {preview}")
            eprint(f"   Reason: {error_reason}")
            user_prompt = _build_pr_retry_user_prompt(
                previous_response=response,
                error_reason=error_reason,
                original_user_prompt=original_user_prompt,
            )
        else:
            preview = response.strip()
            if len(preview) > _RETRY_PREVIEW_CHARS:
                preview = preview[:_RETRY_PREVIEW_CHARS] + "..."
            preview = preview if preview else "<empty>"
            eprint(
                f"{tag('WARN')} LLM produced malformed PR description after "
                f"{_MAX_RETRIES + 1} attempts — using as-is."
            )
            eprint(f"   LLM returned: {preview}")
            eprint(f"   Last failure: {error_reason}")
            return validated_title, validated_body, -1

    return "", "", 1


def run_pr(args: object) -> int:
    """Execute the PR workflow."""
    work_dir = Path.cwd()

    if not git_ops.is_git_repo(work_dir):
        eprint(f"{tag('ERROR')} Not a git repository.")
        return 1

    source = getattr(args, "source", None) or git_ops.get_current_branch(work_dir)
    if not source:
        eprint(f"{tag('ERROR')} Cannot determine current branch.")
        return 1

    target = getattr(args, "target", None) or "main"
    generate_only = getattr(args, "generate", False)
    browser_mode = getattr(args, "browser_mode", False)
    dry_run = getattr(args, "dry_run", False)

    config = load_git_config(work_dir)
    model = get_model(config)

    diff = git_ops.get_diff(target, work_dir)
    log = git_ops.get_log(target, work_dir)

    if not diff.strip() and not log.strip():
        eprint(f"{tag('WARN')} No changes between {target} and {source}.")
        return 0

    changed_files = []
    for line in diff.split("\n"):
        if line.startswith("diff --git"):
            parts = line.split(" b/")
            if len(parts) > 1:
                changed_files.append(parts[-1])

    template = get_template(config, "pr_description")
    system_prompt = _build_pr_system_prompt(config, template)
    files_list = "\n".join(f"- {f}" for f in changed_files[:20])
    max_diff_len = 8000
    truncated_diff = diff[:max_diff_len] + "\n... (truncated)" if len(diff) > max_diff_len else diff
    user_prompt = (
        f"Source branch: {source}\n"
        f"Target branch: {target}\n\n"
        f"Commits since {target}:\n{log}\n\n"
        f"Files changed:\n{files_list}\n\n"
        f"Diff:\n{truncated_diff}\n\n"
        f"PR body template to fill in:\n{template}"
    )

    pr_title, pr_body, rc = _generate_pr_message(
        model, system_prompt, user_prompt, work_dir
    )
    if rc != -1:
        return rc

    eprint(f"{tag('PR')} Generated:\n  Title: {pr_title}\n")
    eprint(f"  Body:\n{pr_body}\n")

    if dry_run or generate_only:
        eprint(f"{tag('INFO')} {'Dry run' if dry_run else 'Generate only'} — no action taken.")
        return 0

    choice = _prompt_user("Confirm?")
    if choice == "n":
        eprint(f"{tag('SKIP')} PR creation aborted.")
        return 0

    if not browser_mode and _gh_available():
        eprint(f"{tag('PR')} Creating PR via gh CLI...")
        ok, output = _create_pr_gh(source, target, pr_title, pr_body, work_dir)
        if ok:
            eprint(f"{tag('OK')} PR created successfully.")
            eprint(output.strip())
            return 0
        else:
            eprint(f"{tag('WARN')} gh CLI failed, falling back to browser mode.")
            eprint(output.strip())

    remote_url = git_ops.get_remote_url(work_dir)
    if not remote_url:
        eprint(f"{tag('ERROR')} Cannot determine remote URL.")
        return 1

    owner_repo = git_ops.parse_remote_owner_repo(remote_url)
    if not owner_repo:
        eprint(f"{tag('ERROR')} Cannot parse remote URL: {remote_url}")
        return 1

    owner, repo = owner_repo
    encoded_title = urllib.parse.quote(pr_title)
    encoded_body = urllib.parse.quote(pr_body)
    url = (
        f"https://github.com/{owner}/{repo}"
        f"/compare/{target}...{source}"
        f"?title={encoded_title}&body={encoded_body}"
    )

    eprint(f"{tag('PR')} Opening browser...")
    if _open_browser(url):
        eprint(f"{tag('OK')} Browser opened with PR creation URL.")
    else:
        eprint(f"{tag('INFO')} URL:\n{url}")

    return 0
